CREATE DATABASE COLLEGE;
USE COLLEGE;

DROP TABLE IF EXISTS DEPARTMENT;
DROP TABLE IF EXISTS STUDENTS;
DROP TABLE IF EXISTS COURSES;

CREATE TABLE DEPARTMENT (
    DeptID INT PRIMARY KEY,
    DepName VARCHAR(50) NOT NULL UNIQUE,
    Location VARCHAR(50) NOT NULL
);

CREATE TABLE STUDENT(
    StudentID INT PRIMARY KEY,
    Name VARCHAR(50) NOT NULL,
    Email VARCHAR(100) NOT NULL UNIQUE,
    CGPA INT,
    DeptID INT,
    FOREIGN KEY (DeptID) REFERENCES DEPARTMENT(DeptID)
        ON DELETE CASCADE
);

CREATE TABLE COURSE(
    CourseID INT PRIMARY KEY,
    CourseName VARCHAR(50) NOT NULL UNIQUE,
    Credits INT CHECK (Credits BETWEEN 1 AND 5),
    StudentID INT,
    Marks INT,
    FOREIGN KEY (StudentID) REFERENCES STUDENT(StudentID)
        ON DELETE CASCADE,
    DeptID INT NULL,  
    FOREIGN KEY (DeptID) REFERENCES DEPARTMENT(DeptID)
        ON DELETE SET NULL
);
INSERT INTO DEPARTMENT VALUES 
(10, 'CSE', 'RBU'),
(20, 'ECE', 'RBU');

INSERT INTO STUDENT VALUES 
(1, 'Aditi', 'aditi@gmail.com', 85, 10);
INSERT INTO STUDENT VALUES 
(2, 'Riya', 'riya@gmail.com', 45, 20);

INSERT INTO COURSE VALUES 
(101, 'DBMS', 4, 1, 66,10);


SELECT S.Name, D.DepName FROM STUDENT AS S
JOIN DEPARTMENT AS D ON S.DeptID = D.DeptID;

SELECT S.Name, D.Location FROM STUDENT AS S
JOIN DEPARTMENT AS D ON S.DeptID = D.DeptID;

SELECT S.Name, D.DepName, S.CGPA FROM STUDENT AS S
JOIN DEPARTMENT AS D ON S.DeptID = D.DeptID WHERE CGPA > 80;

SELECT D.DepName
FROM DEPARTMENT D
LEFT JOIN STUDENT S ON D.DeptID = S.DeptID
WHERE S.StudentID IS NULL;

SELECT S.Name, D.DepName, C.CourseName
FROM STUDENT S
JOIN DEPARTMENT D ON S.DeptID = D.DeptID
JOIN COURSE C ON S.StudentID = C.StudentID;

SELECT S.Name, C.CourseName, C.Marks, S.CGPA
FROM STUDENT S
JOIN COURSE C ON S.StudentID = C.StudentID
WHERE S.CGPA > 70;

SELECT S.Name, D.DepName, COUNT(C.CourseID) as cousrecount
FROM DEPARTMENT D JOIN STUDENT S ON D.DeptID = S.DeptID 
LEFT JOIN COURSE C ON S.StudentID = C.StudentID
GROUP BY D.DepName, S.Name;

SELECT S.Name
FROM STUDENT S
LEFT JOIN COURSE C ON S.StudentID = C.StudentID
WHERE C.CourseID IS NULL;

SELECT D.DepName, COUNT(C.CourseID) AS CourseCount
FROM DEPARTMENT D
LEFT JOIN COURSE C ON D.DeptID = C.DeptID
GROUP BY D.DepName;
