-- TRIGGERS

CREATE TABLE USER_LOG(
ID INT auto_increment PRIMARY KEY,
USER_ID INT ,
NAME VARCHAR(100),
CREATED_ON timestamp default current_timestamp
);

DELIMITER $$

CREATE TRIGGER AFTER_INSERT
AFTER INSERT ON USERS
FOR EACH ROW 
BEGIN
	INSERT INTO USER_LOG(USER_ID, NAME)
    VALUE (NEW.ID , NEW.NAME);
END $$

DELIMITER ;

INSERT INTO USERS ( NAME , EMAIL, GENDER , DATE_OF_BIRTH,  SALARY ) VALUES  
('ROHAN','ROHAN@GMAIL.COM', 'MALE', '2007-02-01' , 90000 );

SELECT * FROM USER_LOG;

SELECT * FROM USERS;

-- DROP TRIGGER IF EXISTS AFTER_INSERT

-- more on sql
SELECT * FROM  USERS WHERE NAME LIKE '_a%' ;

SELECT * FROM USERS ORDER BY ID LIMIT 5 OFFSET 10;

SELECT DISTINCT GENDER FROM USERS;

-- TRUNCATE TABLE USERS

ALTER TABLE USERS
CHANGE COLUMN CITY LOCATION VARCHAR(150);

ALTER TABLE USERS
MODIFY COLUMN SALARY BIGINT;