USE startersql;
SELECT * FROM users;

-- SELECT * FROM USERS WHERE GENDER<>'MALE';

-- SELECT * FROM USERS WHERE ID > 10;
-- SELECT * FROM USERS WHERE GENDER IS NULL;
-- SELECT * FROM USERS WHERE ID BETWEEN '4' AND '10';

-- SELECT * FROM USERS WHERE GENDER IN ('MALE');
-- SELECT * FROM USERS WHERE GENDER='MALE' AND SALARY>'65000' ORDER BY ID ASC;

-- UPDATE USERS SET SALARY=40000, EMAIL = 'ADU@GMAIL.COM' WHERE ID = 1;

-- UPDATE USERS
-- SET SALARY = SALARY+10000  
-- WHERE SALARY < 60000;
SET SQL_SAFE_UPDATES = 0;

-- DELETE FROM USERS WHERE ID=3;

ALTER TABLE USERS MODIFY COLUMN NAME VARCHAR(100) UNIQUE;

INSERT INTO users (name, email, gender, date_of_birth, salary) VALUES
(NULL, 'ADv@example.com', 'Male', '1995-05-14', 65000.00);
SELECT * FROM users;

ALTER TABLE USERS
MODIFY COLUMN NAME VARCHAR(100) NOT NULL ;

DELETE FROM USERS WHERE ID=26;

INSERT INTO users (name, email, gender, date_of_birth, salary) VALUES
('AAAAV', 'ADv@example.com', 'Male', '1995-05-14', 65000.00);

SELECT GENDER, SUM(SALARY) AS SUM_SALARY FROM USERS GROUP BY GENDER;
SELECT GENDER, AVG(SALARY) AS AVG_SALARY FROM USERS GROUP BY GENDER;

INSERT INTO users (name, email, gender, date_of_birth, salary) VALUES
('ADDITI', 'ADITI@ee.com', 'FEMale', '2007-01-02', 65000.00);

SELECT NAME, DATEDIFF(CURDATE(),DATE_OF_BIRTH) AS DAY FROM USERS WHERE ID=30;

SET AUTOCOMMIT = 0;
COMMIT;

DELETE FROM USERS WHERE ID = 5;
ROLLBACK;

SET AUTOCOMMIT = 1; -- BY DEFAULT IT IS ON


